= Activate-Web

image:https://img.shields.io/npm/v/activate-web?style=flat-square[npm]

The "Activate Windows" watermark ported to *Open Web ™*.
Inspired by https://github.com/MrGlockenspiel/activate-linux[activate-linux].

As of 0.1, it's a Web Component written in TypeScript, with a simply packed React component.
The old class based version stayed at 0.0.x.

It's intended as a parody, although still customizeable in both style and content.

React demo at https://activate-web-demo.netlify.app,
vanilla https://activate-web-demo.netlify.app/vanilla.html.

== Usage

=== Vanilla

[source,html]
----
<body>
	<!-- other important things -->

	<activate-web name="The Open Web" gotoText="Donate" gotoLink="https://opencollective.com/theopenweb"></activate-web>
	<!-- the link above is an example -->
	<script type="module">
		import Activate from 'https://esm.run/activate-web'
		Activate.activate()
	</script>
</body>
----

=== React

----
$ npm install --save activate-web
----

[source,jsx]
----
import Activate from 'activate-web/react'

Activate.activate()

export default App() {
	return (
		{...otherImportantThings}

		<Activate
		name='The Open Web'
		gotoText='Donate'
		gotoLink='https://opencollective.com/theopenweb'
		/>
	)
}
----

== Interface

[source,javascript]
----
import Activate from 'activate'
----

==== `Activate.activate(tagName: string = 'activate-web')`

This static method will register itself as `tagName` in `window.customElements`
if no other custom element was registered in that name,
and upgrade existing elements if any present.

=== React

[source,javascript]
----
import Activate from 'activate-web/react'
----

The React version uses the default tag name `activate-web`,
so don't `Activate.activate('another-tag')`.

== Attributes

These attributes are shared between vanilla and React versions.

- `name?: string` as in title line: `Activate ${name}`
- `gotoText?: string, gotoLink?: string` as in detail line:
`Go to <a href="${gotoLink}">${gotoText}</a> to activate ${name}`
- `titleHtml?: string, detailHtml?: string` custom HTML of respective parts, usually set together;
updated using `innerHTML`, so *only trusted input can be passed in*,
and no React component or other fancy stuff (do tell me how though)

The `Html` attributes can be used for more personalized text, or i18n, for example.

All attributes filter out "falsy" strings: `'false'`, `'null'`, `'undefined'`,
except `Html` ones, which silently sets themselves to empty string (`''`),
thus reverting to default format.

== Styling

Assume the custom element is registered as `tag-name`, use the following selectors:

- `tag-name` to style the host element
- `tag-name::part(title)` to style the title part
- `tag-name::part(detail)` to style the detail part

Be sure to override the `opacity` and `filter` properties if you want the text to have visible color.

The default style is written in plain CSS, at `import { DEFAULT_STYLES } from 'activate-web/lib.ts'`.

== License

BSD 3-clause &copy; 2022 Blair Noctis.
